"use strict"
const J = require("../common")
const express = require("express")
const path = require("path")
const favicon = require("serve-favicon")
const bodyParser = require("body-parser")
const route = require("./routes/alt.js")
//const route = require("./routes/index.js")
let app = express()
app.use((req, res, next) =>{
    res.header("Access-Control-Allow-Origin", "*")
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
    next()
})
app.set("views", __dirname + "/views")
app.set("view engine", "pug")
app.use(favicon(__dirname + "/public/favicon.ico"))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(express.static(path.join(__dirname, "public")))
app.use("/", route)
app.use((req, res)=>{
    res.send("ERROR!!")
})
module.exports = app
