module.exports.bulma = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.1.0/css/bulma.min.css"
module.exports.fontAwesome = "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
module.exports.animate = "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css"
module.exports.reactSelect = "https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.min.css"
module.exports.screenLog = "http://ilearnsmarter.com/js/screenLog.js"
module.exports.models = ["main", "translateDraft", "counter"]
module.exports.badQuery = "Bad Query Message!"
module.exports.incomleteRequest = "Incomplete Request Message!"
module.exports.mongooseConnection = "mongodb://localhost/ils"
