module.exports.bulma = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.1.0/css/bulma.min.css"
module.exports.fontAwesome = "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
module.exports.animate = "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css"
module.exports.reactSelect = "https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.min.css"
module.exports.screenLog = "http://ilearnsmarter.com/js/screenLog.js"
module.exports.models = ["main", "translateDraft", "counter"]
module.exports.badQuery = "Bad Query Message!"
module.exports.goodQuery = "Alles in Ordnung"
module.exports.incomleteRequest = "Incomplete Request Message!"
module.exports.mongooseConnection = "mongodb://localhost/ils"
let reactAlertBase = "https://npmcdn.com/react-s-alert@1.1.4"
module.exports.reactAlertDefault = `${reactAlertBase}/dist/s-alert-default.css`
module.exports.reactAlertSlide = `${reactAlertBase}/dist/s-alert-css-effects/slide.css`
module.exports.reactAlertScale = `${reactAlertBase}/dist/s-alert-css-effects/scale.css`
module.exports.reactAlertBouncyflip = `${reactAlertBase}/dist/s-alert-css-effects/bouncyflip.css`
module.exports.reactAlertFlip = `${reactAlertBase}/dist/s-alert-css-effects/flip.css`
module.exports.reactAlertGenie = `${reactAlertBase}/dist/s-alert-css-effects/genie.css`
module.exports.reactAlertJelly = `${reactAlertBase}/dist/s-alert-css-effects/jelly.css`
module.exports.reactAlertStackslide = `${reactAlertBase}/dist/s-alert-css-effects/stackslide.css`
